Make chat filter only load once and general cleanup
RaefWolfe/guildspamsilencer pull request #1
Opened 2024-09-04 20:32 UTC by jammer

Removed the achievement "mute" feature that never activated because the particular achievements are not triggered.

Changed chat filter to load during PLAYER_ENTERING_WORLD event thus making it only load once instead of every join message.

Removed unnecessary checks from OnEvent as it is only registered for one event.

2024-09-04 20:34 UTC, jammer commented
Current released version adds new chat filter every time someone joins the game. I'm unsure how much this will effect performance since the filter is rather simple, but seems like unnecessary load for long play sessions.

2024-09-04 23:18 UTC, RaefWolfe requested changes
When I make these changes the noise from guild achievements still fires, even though the toast does not.

2024-09-05 20:53 UTC, jammer commented
Sorry, I mistakenly assumed the sound was tied to the alert popup, but apparently not. I just added back the previous mute functionality into the alert function.

2024-09-05 22:59 UTC, RaefWolfe approved these changes

2024-09-05 22:59 UTC, merged